---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: windows-8.1

suites:
  - name: default
    run_list:
      - recipe[chef-appbundle-updater::default]
    attributes:
