name             'chef-appbundle-updater'
maintainer       'Jay Mundrawala'
maintainer_email 'jdmundrawala@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures chef-appbundle-updater'
long_description 'Installs/Configures chef-appbundle-updater'
version          '0.0.8'

depends 'build-essential', '~> 2.2.3'
depends 'apt', '~> 2.7.0'
