name             'chef-appbundle-updater'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures chef-appbundle-updater'
long_description 'Installs/Configures chef-appbundle-updater'
version          '0.1.0'

depends 'build-essential', '~> 2.2.3'
depends 'apt', '~> 2.7.0'
